future: false
markdown: kramdown
permalink: ":categories/:title.html"
timezone: Europe/London
plugins:
  - jekyll-feed
title: Peter Hilton’s blog
author: Peter Hilton
description: Product management, software development, and other curiosities
