name: Publish at 09:00 on Tuesdays

on:
  schedule:
   - cron: '0 9 * * 2'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/hilton/hilton.github.com/pages/builds"
